export const POKEMON = [
    {
        id: 0,
        number: "#001",
        name: "Bulbasaur",
        description: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.", 
        evolves: true,
        evolutionId: 0,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/001.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "2'04\"", 
        weight: "15.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 1,
        number: "#002",
        name: "Ivysaur",
        description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", 
        evolves: true,
        evolutionId: 0,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/002.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "3'04\"", 
        weight: "28.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 2,
        number: "#003",
        name: "Venusaur",
        description: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.", 
        evolves: false,
        evolutionId: 0,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/003.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "6'07\"", 
        weight: "220.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 3,
        number: "#004",
        name: "Charmander",
        description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.", 
        evolves: true,
        evolutionId: 3,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/004.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "3'07\"", 
        weight: "41.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 4,
        number: "#005",
        name: "Charmeleon",
        description: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.", 
        evolves: true,
        evolutionId: 3,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/005.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "2'00\"", 
        weight: "18.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 5,
        number: "#006",
        name: "Charizard",
        description: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.", 
        evolves: false,
        evolutionId: 3,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/006.png", 
        type: ["Fire", "Flying"], 
        weakness: ["Water", "Electric", "Rock"],
        height: "5'07\"", 
        weight: "199.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 6,
        number: "#007",
        name: "Squirtle",
        description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.", 
        evolves: true,
        evolutionId: 6,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Turtle",
        image: "/assets/images/007.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "1'08\"", 
        weight: "19.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 7,
        number: "#008",
        name: "Wartortle",
        description: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.", 
        evolves: true,
        evolutionId: 6,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Turtle",
        image: "/assets/images/008.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'03\"", 
        weight: "49.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 8,
        number: "#009",
        name: "Blastoise",
        description: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.", 
        evolves: false,
        evolutionId: 6, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Shellfish",
        image: "/assets/images/009.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "5'03\"", 
        weight: "188.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 9,
        number: "#010",
        name: "Caterpie",
        description: "For protection, it releases a horrible stench from the antenna on its head to drive away enemies.", 
        evolves: true,
        evolutionId: 9, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Worm",
        image: "/assets/images/010.png", 
        type: ["Bug"], 
        weakness: ["Fire", "Flying", "Rock"],
        height: "1'00\"", 
        weight: "6.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 10,
        number: "#011",
        name: "Metapod",
        description: "It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.", 
        evolves: true,
        evolutionId: 9, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Cocoon",
        image: "/assets/images/011.png", 
        type: ["Bug"], 
        weakness: ["Fire", "Flying", "Rock"],
        height: "2'04\"", 
        weight: "21.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 11,
        number: "#012",
        name: "Butterfree",
        description: "In battle, it flaps its wings at great speed to release highly toxic dust into the air.", 
        evolves: false,
        evolutionId: 9, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Butterfly",
        image: "/assets/images/012.png", 
        type: ["Bug", "Flying"], 
        weakness: ["Fire", "Flying","Electric", "Ice", "Rock"],
        height: "3'07\"", 
        weight: "70.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 12,
        number: "#013",
        name: "Weedle",
        description: "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.", 
        evolves: true,
        evolutionId: 12, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Hairy Bug",
        image: "/assets/images/013.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Flying", "Psychic", "Rock"],
        height: "1'00\"", 
        weight: "7.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 13,
        number: "#014",
        name: "Kakuna",
        description: "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.", 
        evolves: true,
        evolutionId: 12, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Cocoon",
        image: "/assets/images/014.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Rock"],
        height: "2'00\"", 
        weight: "22.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 14,
        number: "#015",
        name: "Beedrill",
        description: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.", 
        evolves: false,
        evolutionId: 12, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Poison Bee",
        image: "/assets/images/015.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Rock"],
        height: "3'03\"", 
        weight: "65.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 15,
        number: "#016",
        name: "Pidgy",
        description: "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.", 
        evolves: true,
        evolutionId: 15, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Bird",
        image: "/assets/images/016.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "1'00\"", 
        weight: "4.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 16,
        number: "#017",
        name: "Pidgeotto",
        description: "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.", 
        evolves: true,
        evolutionId: 15, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bird",
        image: "/assets/images/017.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "3'07\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 17,
        number: "#018",
        name: "Pidgeot",
        description: "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.", 
        evolves: false,
        evolutionId: 15, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bird",
        image: "/assets/images/018.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "4'11\"", 
        weight: "87.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 18,
        number: "#019",
        name: "Rattata",
        description: "Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.", 
        evolves: true,
        evolutionId: 18, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/019.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "1'00\"", 
        weight: "7.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 19,
        number: "#020",
        name: "Raticate",
        description: "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.", 
        evolves: false,
        evolutionId: 18, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/020.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "2'04\"", 
        weight: "40.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 20,
        number: "#021",
        name: "Spearow",
        description: "Inept at flying high. However, it can fly around very fast to protect its territory.", 
        evolves: true,
        evolutionId: 20, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Bird",
        image: "/assets/images/021.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "1'00\"", 
        weight: "4.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 21,
        number: "#022",
        name: "Fearow",
        description: "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.", 
        evolves: false,
        evolutionId: 20, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Beak",
        image: "/assets/images/022.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "3'11\"", 
        weight: "83.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 22,
        number: "#023",
        name: "Ekans",
        description: "The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.", 
        evolves: true,
        evolutionId: 22, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Snake",
        image: "/assets/images/023.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "6'07\"", 
        weight: "15.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 23,
        number: "#024",
        name: "Arbok",
        description: "The frightening patterns on its belly have been studied. Six variations have been confirmed.", 
        evolves: false,
        evolutionId: 22, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Snake",
        image: "/assets/images/024.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "11'06\"", 
        weight: "143.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 24,
        number: "#025",
        name: "Pikachu",
        description: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.", 
        evolves: true,
        evolutionId: 24, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/025.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "1'04\"", 
        weight: "13.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 25,
        number: "#026",
        name: "Raichu",
        description: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.", 
        evolves: false,
        evolutionId: 24, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/026.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "2'07\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
]
