export const POKEMON = [
    {
        id: 0,
        number: "#001",
        name: "Bulbasaur",
        description: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.", 
        evolves: true,
        evolvesInto: "Ivysaur", 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/001.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "2'04\"", 
        weight: "15.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 1,
        number: "#002",
        name: "Ivysaur",
        description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", 
        evolves: true,
        evolvesInto: "Venusaur", 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/002.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "3'04\"", 
        weight: "28.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 2,
        number: "#003",
        name: "Venusaur",
        description: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.", 
        evolves: false,
        evolvesInto: "", 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/003.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "6'07\"", 
        weight: "220.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 3,
        number: "#004",
        name: "Charmander",
        description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.", 
        evolves: true,
        evolvesInto: "Charmeleon", 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/004.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "3'07\"", 
        weight: "41.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 4,
        number: "#005",
        name: "Charmeleon",
        description: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.", 
        evolves: true,
        evolvesInto: "Charizard", 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/005.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "2'00\"", 
        weight: "18.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 5,
        number: "#006",
        name: "Charizard",
        description: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.", 
        evolves: false,
        evolvesInto: "Charizard", 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/006.png", 
        type: ["Fire", "Flying"], 
        weakness: ["Water", "Electric", "Rock"],
        height: "5'07\"", 
        weight: "199.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 6,
        number: "#007",
        name: "Squirtle",
        description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.", 
        evolves: true,
        evolvesInto: "Wartortle", 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Turtle",
        image: "/assets/images/007.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "1'08\"", 
        weight: "19.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 7,
        number: "#008",
        name: "Wartortle",
        description: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.", 
        evolves: true,
        evolvesInto: "Blastoise", 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Turtle",
        image: "/assets/images/008.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'03\"", 
        weight: "49.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 8,
        number: "#009",
        name: "Blastoise",
        description: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.", 
        evolves: false,
        evolvesInto: "", 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Shellfish",
        image: "/assets/images/009.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "5'03\"", 
        weight: "188.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    }
]