export const POKEMON = [
    {
        id: 0,
        number: "#001",
        name: "Bulbasaur",
        description: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.", 
        evolves: true,
        evolutionId: 0,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/001.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "2'04\"", 
        weight: "15.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 1,
        number: "#002",
        name: "Ivysaur",
        description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", 
        evolves: true,
        evolutionId: 0,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/002.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "3'04\"", 
        weight: "28.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 2,
        number: "#003",
        name: "Venusaur",
        description: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.", 
        evolves: false,
        evolutionId: 0,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Seed",
        image: "/assets/images/003.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "6'07\"", 
        weight: "220.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 3,
        number: "#004",
        name: "Charmander",
        description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.", 
        evolves: true,
        evolutionId: 3,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/004.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "3'07\"", 
        weight: "41.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 4,
        number: "#005",
        name: "Charmeleon",
        description: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.", 
        evolves: true,
        evolutionId: 3,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/005.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "2'00\"", 
        weight: "18.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 5,
        number: "#006",
        name: "Charizard",
        description: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.", 
        evolves: false,
        evolutionId: 3,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/006.png", 
        type: ["Fire", "Flying"], 
        weakness: ["Water", "Electric", "Rock"],
        height: "5'07\"", 
        weight: "199.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 6,
        number: "#007",
        name: "Squirtle",
        description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.", 
        evolves: true,
        evolutionId: 6,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Turtle",
        image: "/assets/images/007.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "1'08\"", 
        weight: "19.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 7,
        number: "#008",
        name: "Wartortle",
        description: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.", 
        evolves: true,
        evolutionId: 6,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Turtle",
        image: "/assets/images/008.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'03\"", 
        weight: "49.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 8,
        number: "#009",
        name: "Blastoise",
        description: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.", 
        evolves: false,
        evolutionId: 6, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Shellfish",
        image: "/assets/images/009.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "5'03\"", 
        weight: "188.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 9,
        number: "#010",
        name: "Caterpie",
        description: "For protection, it releases a horrible stench from the antenna on its head to drive away enemies.", 
        evolves: true,
        evolutionId: 9, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Worm",
        image: "/assets/images/010.png", 
        type: ["Bug"], 
        weakness: ["Fire", "Flying", "Rock"],
        height: "1'00\"", 
        weight: "6.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 10,
        number: "#011",
        name: "Metapod",
        description: "It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.", 
        evolves: true,
        evolutionId: 9, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Cocoon",
        image: "/assets/images/011.png", 
        type: ["Bug"], 
        weakness: ["Fire", "Flying", "Rock"],
        height: "2'04\"", 
        weight: "21.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 11,
        number: "#012",
        name: "Butterfree",
        description: "In battle, it flaps its wings at great speed to release highly toxic dust into the air.", 
        evolves: false,
        evolutionId: 9, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Butterfly",
        image: "/assets/images/012.png", 
        type: ["Bug", "Flying"], 
        weakness: ["Fire", "Flying","Electric", "Ice", "Rock"],
        height: "3'07\"", 
        weight: "70.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 12,
        number: "#013",
        name: "Weedle",
        description: "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.", 
        evolves: true,
        evolutionId: 12, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Hairy Bug",
        image: "/assets/images/013.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Flying", "Psychic", "Rock"],
        height: "1'00\"", 
        weight: "7.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 13,
        number: "#014",
        name: "Kakuna",
        description: "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.", 
        evolves: true,
        evolutionId: 12, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Cocoon",
        image: "/assets/images/014.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Rock"],
        height: "2'00\"", 
        weight: "22.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 14,
        number: "#015",
        name: "Beedrill",
        description: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.", 
        evolves: false,
        evolutionId: 12, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Poison Bee",
        image: "/assets/images/015.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Rock"],
        height: "3'03\"", 
        weight: "65.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 15,
        number: "#016",
        name: "Pidgey",
        description: "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.", 
        evolves: true,
        evolutionId: 15, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Bird",
        image: "/assets/images/016.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "1'00\"", 
        weight: "4.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 16,
        number: "#017",
        name: "Pidgeotto",
        description: "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.", 
        evolves: true,
        evolutionId: 15, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bird",
        image: "/assets/images/017.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "3'07\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 17,
        number: "#018",
        name: "Pidgeot",
        description: "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.", 
        evolves: false,
        evolutionId: 15, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bird",
        image: "/assets/images/018.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "4'11\"", 
        weight: "87.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 18,
        number: "#019",
        name: "Rattata",
        description: "Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.", 
        evolves: true,
        evolutionId: 18, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/019.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "1'00\"", 
        weight: "7.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 19,
        number: "#020",
        name: "Raticate",
        description: "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.", 
        evolves: false,
        evolutionId: 18, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/020.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "2'04\"", 
        weight: "40.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 20,
        number: "#021",
        name: "Spearow",
        description: "Inept at flying high. However, it can fly around very fast to protect its territory.", 
        evolves: true,
        evolutionId: 20, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tiny Bird",
        image: "/assets/images/021.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "1'00\"", 
        weight: "4.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 21,
        number: "#022",
        name: "Fearow",
        description: "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.", 
        evolves: false,
        evolutionId: 20, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Beak",
        image: "/assets/images/022.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "3'11\"", 
        weight: "83.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 22,
        number: "#023",
        name: "Ekans",
        description: "The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.", 
        evolves: true,
        evolutionId: 22, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Snake",
        image: "/assets/images/023.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "6'07\"", 
        weight: "15.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 23,
        number: "#024",
        name: "Arbok",
        description: "The frightening patterns on its belly have been studied. Six variations have been confirmed.", 
        evolves: false,
        evolutionId: 22, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Snake",
        image: "/assets/images/024.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "11'06\"", 
        weight: "143.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 24,
        number: "#025",
        name: "Pikachu",
        description: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.", 
        evolves: true,
        evolutionId: 24, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/025.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "1'04\"", 
        weight: "13.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 25,
        number: "#026",
        name: "Raichu",
        description: "Its long tail serves as a ground to protect itself from its own high-voltage power.", 
        evolves: false,
        evolutionId: 24, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/026.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "2'07\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 26,
        number: "#027",
        name: "Sandshrew",
        description: "It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body.",
        evoldes: true,
        evolutionId: 26,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/027.png", 
        type: ["Ground"], 
        weakness: ["Water", "Grass", "Ice"],
        height: "2'00\"", 
        weight: "26.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 27,
        number: "#028",
        name: "Sandslash",
        description: "The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched.", 
        evolves: false,
        evolutionId: 26,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mouse",
        image: "/assets/images/028.png", 
        type: ["Ground"], 
        weakness: ["Water", "Grass", "Ice"],
        height: "3'03\"", 
        weight: "65. LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 28,
        number: "#029",
        name: "Nidoran",
        description: "Females are more sensitive to smells than males. While foraging, they’ll use their whiskers to check wind direction and stay downwind of predators.", 
        evolves: true,
        evolutionId: 28,
        middleEvolution: false,
        baby: false,
        gender: ["Female"],
        category: "Poison Pin",
        image: "/assets/images/029.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "1'04\"", 
        weight: "15.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 29,
        number: "#030",
        name: "Nidorina",
        description: "The horn on its head has atrophied. It’s thought that this happens so Nidorina’s children won’t get poked while their mother is feeding them.", 
        evolves: true,
        evolutionId: 28,
        middleEvolution: true,
        baby: false,
        gender: ["Female"],
        category: "Poison Pin",
        image: "/assets/images/030.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "2'07\"", 
        weight: "44.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 30,
        number: "#031",
        name: "Nidoqueen",
        description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.", 
        evolves: false,
        evolutionStone: "Moon Stone",
        evolutionId: 28,
        middleEvolution: false,
        baby: false,
        gender: ["Female"],
        category: "Drill",
        image: "/assets/images/031.png", 
        type: ["Poison", "Ground"], 
        weakness: ["Water", "Ground", "Psychic", "Ice"],
        height: "4'03\"", 
        weight: "132.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 31,
        number: "#032",
        name: "Nidoran",
        description: "The horn on a male Nidoran’s forehead contains a powerful poison. This is a very cautious Pokémon, always straining its large ears.", 
        evolves: true,
        evolutionId: 31,
        middleEvolution: false,
        baby: false,
        gender: ["Male"],
        category: "Poison Pin",
        image: "/assets/images/032.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "1'08\"", 
        weight: "19.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 32,
        number: "#033",
        name: "Nidorino",
        description: "With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone.", 
        evolves: true,
        evolutionId: 31,
        middleEvolution: true,
        baby: false,
        gender: ["Male"],
        category: "Poison Pin",
        image: "/assets/images/033.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "2'11\"", 
        weight: "43.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 33,
        number: "#034",
        name: "Nidoking",
        description: "When it goes on a rampage, it’s impossible to control. But in the presence of a Nidoqueen it’s lived with for a long time, Nidoking calms down.", 
        evolves: false,
        evolutionStone: "Moon Stone",
        evolutionId: 31,
        middleEvolution: false,
        baby: false,
        gender: ["Male"],
        category: "Drill",
        image: "/assets/images/034.png", 
        type: ["Poison", "Ground"], 
        weakness: ["Water", "Ground", "Psychic", "Ice"],
        height: "4'07\"", 
        weight: "136.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 34,
        number: "#035",
        name: "Clefairy",
        description: "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.", 
        evolves: true,
        evolutionId: 34,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fairy",
        image: "/assets/images/035.png", 
        type: ["Fairy"], 
        weakness: ["Steel", "Poison"],
        height: "2'00\"", 
        weight: "16.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 35,
        number: "#036",
        name: "Clefable",
        description: "A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people.", 
        evolves: false,
        evolutionStone: "Moon Stone",
        evolutionId: 34, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fairy",
        image: "/assets/images/036.png", 
        type: ["Fairy"], 
        weakness: ["Steel", "Poison"],
        height: "4'03\"", 
        weight: "88.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 36,
        number: "#037",
        name: "Vulpix",
        description: "While young, it has six gorgeous tails. When it grows, several new tails are sprouted.", 
        evolves: true,
        evolutionId: 36, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fox",
        image: "/assets/images/037.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "2'00\"", 
        weight: "21,8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 37,
        number: "#038",
        name: "Ninetales",
        description: "It is said to live 1,000 years, and each of its tails is loaded with supernatural powers.", 
        evolves: false,
        evolutionId: 36, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fox",
        image: "/assets/images/038.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "3'07\"", 
        weight: "43.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 38,
        number: "#039",
        name: "Jigglypuff",
        description: "Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep.", 
        evolves: true,
        evolutionId: 38, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Balloon",
        image: "/assets/images/039.png", 
        type: ["Normal", "Fairy"], 
        weakness: ["Steel", "Poison"],
        height: "1'08\"", 
        weight: "12.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 39,
        number: "#040",
        name: "Wigglytuff",
        description: "The more air it takes in, the more it inflates. If opponents catch it in a bad mood, it will inflate itself to an enormous size to intimidate them.", 
        evolves: false,
        evolutionId: 38, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Balloon",
        image: "/assets/images/040.png", 
        type: ["Normal", "Fairy"], 
        weakness: ["Steel", "Poison"],
        height: "3'03\"", 
        weight: "26.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 40,
        number: "#041",
        name: "Zubat",
        description: "It emits ultrasonic waves from its mouth to check its surroundings. Even in tight caves, Zubat flies around with skill.", 
        evolves: true,
        evolutionId: 40, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bat",
        image: "/assets/images/041.png", 
        type: ["Flying", "Poison"], 
        weakness: ["Electric", "Ice","Psychic", "Rock"],
        height: "2'07\"", 
        weight: "16.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 41,
        number: "#042",
        name: "Golbat",
        description: "It loves to drink other creatures’ blood. It’s said that if it finds others of its kind going hungry, it sometimes shares the blood it’s gathered.", 
        evolves: false,
        evolutionId: 40, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bat",
        image: "/assets/images/042.png", 
        type: ["Flying", "Poison"], 
        weakness: ["Electric", "Ice","Psychic", "Rock"],
        height: "5'03\"", 
        weight: "121.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 42,
        number: "#043",
        name: "Oddish",
        description: "If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds.", 
        evolves: true,
        evolutionId: 42, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Weed",
        image: "/assets/images/043.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "1'08\"", 
        weight: "11.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 43,
        number: "#044",
        name: "Gloom",
        description: "Its pistils exude an incredibly foul odor. The horrid stench can cause fainting at a distance of 1.25 miles.", 
        evolves: true,
        evolutionId: 42, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Weed",
        image: "/assets/images/044.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "2'07\"", 
        weight: "19.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 44,
        number: "#045",
        name: "Vileplume",
        description: "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.", 
        evolves: false,
        evolutionId: 42, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flower",
        image: "/assets/images/045.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Psychic", "Flying", "Ice"],
        height: "3'11\"", 
        weight: "41.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 45,
        number: "#046",
        name: "Paras",
        description: "Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.", 
        evolves: true,
        evolutionId: 45, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mushroom",
        image: "/assets/images/046.png", 
        type: ["Bug", "Grass"], 
        weakness: ["Fire", "Flying", "Ice", "Poison", "Rock", "Bug"],
        height: "1'00\"", 
        weight: "11.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 46,
        number: "#047",
        name: "Parasect",
        description: "The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking.", 
        evolves: false,
        evolutionId: 45, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mushroom",
        image: "/assets/images/047.png", 
        type: ["Bug", "Grass"], 
        weakness: ["Fire", "Flying", "Ice", "Poison", "Rock", "Bug"],
        height: "3'03\"", 
        weight: "65.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 47,
        number: "#048",
        name: "Venonat",
        description: "Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes.", 
        evolves: true,
        evolutionId: 47, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Insect",
        image: "/assets/images/048.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Psychihc", "Flying", "Rock"],
        height: "3'03\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 48,
        number: "#049",
        name: "Venomoth",
        description: "The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact..", 
        evolves: false,
        evolutionId: 47, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Poison Moth",
        image: "/assets/images/049.png", 
        type: ["Bug", "Poison"], 
        weakness: ["Fire", "Psychihc", "Flying", "Rock"],
        height: "4'11\"", 
        weight: "27.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 49,
        number: "#050",
        name: "Diglett",
        description: "If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops.", 
        evolves: true,
        evolutionId: 49, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mole",
        image: "/assets/images/050.png", 
        type: ["Ground"], 
        weakness: ["Water", "Grass", "Ice"],
        height: "0'08\"", 
        weight: "1.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 50,
        number: "#051",
        name: "Dugtrio",
        description: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.", 
        evolves: false,
        evolutionId: 49, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mole",
        image: "/assets/images/051.png", 
        type: ["Ground"], 
        weakness: ["Water", "Grass", "Ice"],
        height: "2'04\"", 
        weight: "73.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 51,
        number: "#052",
        name: "Meowth",
        description: "It loves to collect shiny things. If it’s in a good mood, it might even let its Trainer have a look at its hoard of treasures.", 
        evolves: true,
        evolutionId: 51, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Scratch Cat",
        image: "/assets/images/052.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "1'04\"", 
        weight: "9.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 52,
        number: "#053",
        name: "Persian",
        description: "Getting this prideful Pokémon to warm up to you takes a lot of effort, and it will claw at you the moment it gets annoyed.", 
        evolves: false,
        evolutionId: 51, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Classy CAt",
        image: "/assets/images/053.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "3'03\"", 
        weight: "70.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 53,
        number: "#054",
        name: "Psyduck",
        description: "Psyduck is constantly beset by headaches. If the Pokémon lets its strange power erupt, apparently the pain subsides for a while.", 
        evolves: true,
        evolutionId: 53,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Duck",
        image: "/assets/images/054.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "2'07\"", 
        weight: "43.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 54,
        number: "#055",
        name: "Golduck",
        description: "This Pokémon lives in gently flowing rivers. It paddles through the water with its long limbs, putting its graceful swimming skills on display.", 
        evolves: false,
        evolutionId: 53,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Duck",
        image: "/assets/images/055.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "5'07\"", 
        weight: "168.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 55,
        number: "#056",
        name: "Mankey",
        description: "An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything.", 
        evolves: true,
        evolutionId: 55,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Pig Monkey",
        image: "/assets/images/056.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying", "Fairy"],
        height: "1'08\"", 
        weight: "61.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 56,
        number: "#057",
        name: "Primeape",
        description: "It stops being angry only when nobody else is around. To view this moment is very difficult.", 
        evolves: false,
        evolutionId: 55,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Pig Monkey",
        image: "/assets/images/057.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying", "Fairy"],
        height: "3'03\"", 
        weight: "70.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 57,
        number: "#058",
        name: "Growlithe",
        description: "It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.", 
        evolves: true,
        evolutionId: 57,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Puppy",
        image: "/assets/images/058.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "2'00\"", 
        weight: "18.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 58,
        number: "#059",
        name: "Arcanine",
        description: "The sight of it running over 6,200 miles in a single day and night has captivated many people.", 
        evolves: false,
        evolutionId: 57,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Legendary",
        image: "/assets/images/059.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "6'03\"", 
        weight: "341.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 59,
        number: "#060",
        name: "Poliwag",
        description: "For Poliwag, swimming is easier than walking. The swirl pattern on its belly is actually part of the Pokémon’s innards showing through the skin.", 
        evolves: true,
        evolutionId: 59,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tadpole",
        image: "/assets/images/060.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "2'00\"", 
        weight: "27.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 60,
        number: "#061",
        name: "Poliwhirl",
        description: "Staring at the swirl on its belly causes drowsiness. This trait of Poliwhirl’s has been used in place of lullabies to get children to go to sleep.", 
        evolves: true,
        evolutionId: 59,
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tadpole",
        image: "/assets/images/061.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'03\"", 
        weight: "44.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 61,
        number: "#062",
        name: "Poliwrath",
        description: "Its body is solid muscle. When swimming through cold seas, Poliwrath uses its impressive arms to smash through drift ice and plow forward.", 
        evolves: false,
        evolutionId: 59,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Tadpole",
        image: "/assets/images/062.png", 
        type: ["Water", "Fighting"], 
        weakness: ["Grass", "Electric", "Fairy", "Flying", "Psychic"],
        height: "4'03\"", 
        weight: "119.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 62,
        number: "#063",
        name: "Abra",
        description: "This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields.", 
        evolves: true,
        evolutionId: 62, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Psi",
        image: "/assets/images/063.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark", "Bug"],
        height: "2'11\"", 
        weight: "43.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 63,
        number: "#064",
        name: "Kadabra",
        description: "Using its psychic power, Kadabra levitates as it sleeps. It uses its springy tail as a pillow.", 
        evolves: true,
        evolutionId: 62, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Psi",
        image: "/assets/images/064.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark", "Bug"],
        height: "4'03\"", 
        weight: "124.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 64,
        number: "#065",
        name: "Alakazam",
        description: "It has an incredibly high level of intelligence. Some say that Alakazam remembers everything that ever happens to it, from birth till death.", 
        evolves: false,
        evolutionId: 62, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Psi",
        image: "/assets/images/065.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark", "Bug"],
        height: "4'11\"", 
        weight: "105.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 65,
        number: "#066",
        name: "Machop",
        description: "Its whole body is composed of muscles. Even though it’s the size of a human child, it can hurl 100 grown-ups.", 
        evolves: true,
        evolutionId: 65, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Superpower",
        image: "/assets/images/066.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying","Fairy"],
        height: "2'07\"", 
        weight: "43.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 66,
        number: "#067",
        name: "Machoke",
        description: "Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.", 
        evolves: true,
        evolutionId: 65, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Superpower",
        image: "/assets/images/067.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying","Fairy"],
        height: "4'11\"", 
        weight: "155.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 67,
        number: "#068",
        name: "Machamp",
        description: "It quickly swings its four arms to rock its opponents with ceaseless punches and chops from all angles.", 
        evolves: false,
        evolutionId: 65, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Superpower",
        image: "/assets/images/068.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying","Fairy"],
        height: "5'03\"", 
        weight: "286.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 68,
        number: "#069",
        name: "Bellsprout",
        description: "Prefers hot and humid places. It ensnares tiny bugs with its vines and devours them.", 
        evolves: true,
        evolutionId: 69, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flower",
        image: "/assets/images/069.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Ice"],
        height: "2'04\"", 
        weight: "8.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 69,
        number: "#070",
        name: "Weepinbell",
        description: "When hungry, it swallows anything that moves. Its hapless prey is dissolved by strong acids.", 
        evolves: true,
        evolutionId: 69, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flycatcher",
        image: "/assets/images/070.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Ice"],
        height: "3'03\"", 
        weight: "14.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 70,
        number: "#071",
        name: "Victreebel",
        description: "Lures prey with the sweet aroma of honey. Swallowed whole, the prey is dissolved in a day, bones and all.", 
        evolves: false,
        evolutionId: 69, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flycatcher",
        image: "/assets/images/071.png", 
        type: ["Grass", "Poison"], 
        weakness: ["Fire", "Flying","Psychic", "Ice"],
        height: "5'07\"", 
        weight: "34.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 71,
        number: "#072",
        name: "Tentacool",
        description: "Tentacool is not a particularly strong swimmer. It drifts across the surface of shallow seas as it searches for prey.", 
        evolves: true,
        evolutionId: 71, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Jellyfish",
        image: "/assets/images/072.png", 
        type: ["Water", "Poison"], 
        weakness: ["Electric", "Ground", "Psychic"],
        height: "2'11\"", 
        weight: "100.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 72,
        number: "#073",
        name: "Tentacruel",
        description: "When the red orbs on Tentacruel’s head glow brightly, watch out. The Pokémon is about to fire off a burst of ultrasonic waves..", 
        evolves: false,
        evolutionId: 71, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Jellyfish",
        image: "/assets/images/073.png", 
        type: ["Water", "Poison"], 
        weakness: ["Electric", "Ground", "Psychic"],
        height: "5'03\"", 
        weight: "121.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 73,
        number: "#074",
        name: "Geodude",
        description: "Commonly found near mountain trails and the like. If you step on one by accident, it gets angry.", 
        evolves: true,
        evolutionId: 73, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Rock",
        image: "/assets/images/074.png", 
        type: ["Rock", "Ground"], 
        weakness: ["Fighting", "Steel", "Water", "Ice", "Grass", "Ground"],
        height: "1'04\"", 
        weight: "44.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 74,
        number: "#075",
        name: "Graveler",
        description: "Often seen rolling down mountain trails. Obstacles are just things to roll straight over, not avoid.", 
        evolves: true,
        evolutionId: 73, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Rock",
        image: "/assets/images/075.png", 
        type: ["Rock", "Ground"], 
        weakness: ["Fighting", "Steel", "Water", "Ice", "Grass", "Ground"],
        height: "3'03\"", 
        weight: "231.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 75,
        number: "#076",
        name: "Golem",
        description: "Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it’s exposed to air.", 
        evolves: false,
        evolutionId: 73, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Megaton",
        image: "/assets/images/076.png", 
        type: ["Rock", "Ground"], 
        weakness: ["Fighting", "Steel", "Water", "Ice", "Grass", "Ground"],
        height: "4'07\"", 
        weight: "661.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 76,
        number: "#077",
        name: "Ponyta",
        description: "It can’t run properly when it’s newly born. As it races around with others of its kind, its legs grow stronger.", 
        evolves: true,
        evolutionId: 76, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fire Horse",
        image: "/assets/images/077.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "3'03\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 77,
        number: "#078",
        name: "Rapidash",
        description: "This Pokémon can be seen galloping through fields at speeds of up to 150 mph, its fiery mane fluttering in the wind.", 
        evolves: false,
        evolutionId: 76, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fire Horse",
        image: "/assets/images/078.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "5'07\"", 
        weight: "209.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 78,
        number: "#079",
        name: "Slowpoke",
        description: "Slow-witted and oblivious, this Pokémon won’t feel any pain if its tail gets eaten. It won’t notice when its tail grows back, either.", 
        evolves: true,
        evolutionId: 78, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dopey",
        image: "/assets/images/079.png", 
        type: ["Water", "Psychic"], 
        weakness: ["Ghost", "Dark", "Grass", "Electric", "Bug"],
        height: "3'11\"", 
        weight: "79.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 79,
        number: "#080",
        name: "Slowbro",
        description: "Slowpoke became Slowbro when a Shellder bit on to its tail. Sweet flavors seeping from the tail make the Shellder feel as if its life is a dream.", 
        evolves: false,
        evolutionId: 78, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dopey",
        image: "/assets/images/080.png", 
        type: ["Water", "Psychic"], 
        weakness: ["Ghost", "Dark", "Grass", "Electric", "Bug"],
        height: "5'03\"", 
        weight: "173.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 80,
        number: "#081",
        name: "Magnemite",
        description: "At times, Magnemite runs out of electricity and ends up on the ground. If you give batteries to a grounded Magnemite, it’ll start moving again..", 
        evolves: true,
        evolutionId: 80, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Magnet",
        image: "/assets/images/081.png", 
        type: ["Electric", "Steel"], 
        weakness: ["Ground", "Fighting", "Fire"],
        height: "1'00\"", 
        weight: "13.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 81,
        number: "#082",
        name: "Magneton",
        description: "This Pokémon is three Magnemite that have linked together. Magneton sends out powerful radio waves to study its surroundings.", 
        evolves: false,
        evolutionId: 80,
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Magnet",
        image: "/assets/images/082.png", 
        type: ["Electric", "Steel"], 
        weakness: ["Ground", "Fighting", "Fire"],
        height: "3'03\"", 
        weight: "132.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 82,
        number: "#083",
        name: "Farfetch'd",
        description: "The stalk this Pokémon carries in its wings serves as a sword to cut down opponents. In a dire situation, the stalk can also serve as food..", 
        evolves: false,
        evolutionId: 82,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Wild Duck",
        image: "/assets/images/083.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "2'07\"", 
        weight: "33.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 83,
        number: "#084",
        name: "Doduo",
        description: "Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs.", 
        evolves: true,
        evolutionId: 83,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Twin Bird",
        image: "/assets/images/084.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "4'07\"", 
        weight: "86.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 84,
        number: "#085",
        name: "Dodrio",
        description: "One of Doduo’s two heads splits to form a unique species. It runs close to 40 mph in prairies.", 
        evolves: false,
        evolutionId: 83,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Triple Bird",
        image: "/assets/images/085.png", 
        type: ["Normal", "Flying"], 
        weakness: ["Electric", "Ice", "Rock"],
        height: "5'11\"", 
        weight: "187.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 85,
        number: "#086",
        name: "Seel",
        description: "Loves freezing-cold conditions. Relishes swimming in a frigid climate of around 14 degrees Fahrenheit.", 
        evolves: true,
        evolutionId: 85,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Sea Lion",
        image: "/assets/images/086.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'07\"", 
        weight: "198.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 86,
        number: "#087",
        name: "Dewgong",
        description: "Its entire body is a snowy white. Unharmed by even intense cold, it swims powerfully in icy waters.", 
        evolves: false,
        evolutionId: 85,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Sea Lion",
        image: "/assets/images/087.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "5'07\"", 
        weight: "264.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 87,
        number: "#088",
        name: "Grimer",
        description: "Made of congealed sludge. It smells too putrid to touch. Even weeds won’t grow in its path.", 
        evolves: true,
        evolutionId: 87,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Sludge",
        image: "/assets/images/088.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "2'11\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 88,
        number: "#089",
        name: "Muk",
        description: "Smells so awful, it can cause fainting. Through degeneration of its nose, it lost its sense of smell.", 
        evolves: false,
        evolutionId: 87,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Sludge",
        image: "/assets/images/089.png", 
        type: ["Poison"], 
        weakness: ["Psychic", "Ground"],
        height: "3'11\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 89,
        number: "#090",
        name: "Shellder",
        description: "It swims facing backward by opening and closing its two-piece shell. It is surprisingly fast.", 
        evolves: true,
        evolutionId: 89, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bivalve",
        image: "/assets/images/090.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "1'00\"", 
        weight: "8.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 90,
        number: "#091",
        name: "Cloyster",
        description: "Its shell is extremely hard. It cannot be shattered, even with a bomb. The shell opens only when it is attacking.", 
        evolves: false,
        evolutionId: 89, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bivalve",
        image: "/assets/images/091.png", 
        type: ["Water", "Ice"], 
        weakness: ["Grass", "Electric", "Fighting", "Rock"],
        height: "4'11\"", 
        weight: "292.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 91,
        number: "#092",
        name: "Gastly",
        description: "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.", 
        evolves: true,
        evolutionId: 91, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Gas",
        image: "/assets/images/092.png", 
        type: ["Ghost", "Poison"], 
        weakness: ["Ghost", "Dark", "Psychic", "Ground"],
        height: "4'03\"", 
        weight: "0.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 92,
        number: "#093",
        name: "Haunter",
        description: "Its tongue is made of gas. If licked, its victim starts shaking constantly until death eventually comes.", 
        evolves: true,
        evolutionId: 91, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Gas",
        image: "/assets/images/093.png", 
        type: ["Ghost", "Poison"], 
        weakness: ["Ghost", "Dark", "Psychic", "Ground"],
        height: "5'03\"", 
        weight: "0.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 93,
        number: "#094",
        name: "Gengar",
        description: "On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.", 
        evolves: false,
        evolutionId: 91, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Shadow",
        image: "/assets/images/094.png", 
        type: ["Ghost", "Poison"], 
        weakness: ["Ghost", "Dark", "Psychic", "Ground"],
        height: "4'11\"", 
        weight: "89.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 94,
        number: "#095",
        name: "Onix",
        description: "As it digs through the ground, it absorbs many hard objects. This is what makes its body so solid.", 
        evolves: false,
        evolutionId: 94, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Rock Snake",
        image: "/assets/images/095.png", 
        type: ["Rock", "Ground"], 
        weakness: ["Steel", "Fighting","Water", "Ice", "Grass", "Ground"],
        height: "28'10\"", 
        weight: "463.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 95,
        number: "#096",
        name: "Drowzee",
        description: "If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past.", 
        evolves: true,
        evolutionId: 95, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Hypnosis",
        image: "/assets/images/096.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark","Bug"],
        height: "3'03\"", 
        weight: "71.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 96,
        number: "#097",
        name: "Hypno",
        description: "Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum.", 
        evolves: false,
        evolutionId: 95, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Hypnosis",
        image: "/assets/images/097.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark","Bug"],
        height: "5'03\"", 
        weight: "166.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 97,
        number: "#098",
        name: "Krabby",
        description: "It can be found near the sea. The large pincers grow back if they are torn out of their sockets.", 
        evolves: true,
        evolutionId: 97, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "River Crab",
        image: "/assets/images/098.png", 
        type: ["Water"], 
        weakness: ["Electric", "Grass"],
        height: "1'04\"", 
        weight: "14.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 98,
        number: "#099",
        name: "Kingler",
        description: "Its large and hard pincer has 10,000-horsepower strength. However, being so big, it is unwieldy to move.", 
        evolves: false,
        evolutionId: 97, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Pincer",
        image: "/assets/images/099.png", 
        type: ["Water"], 
        weakness: ["Electric", "Grass"],
        height: "4'03\"", 
        weight: "132.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 99,
        number: "#100",
        name: "Voltorb",
        description: "It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus.", 
        evolves: true,
        evolutionId: 99, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Ball",
        image: "/assets/images/100.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "1'08\"", 
        weight: "22.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 100,
        number: "#101",
        name: "Electrode",
        description: "Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion.", 
        evolves: false,
        evolutionId: 99, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Ball",
        image: "/assets/images/101.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "3'11\"", 
        weight: "146.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 101,
        number: "#102",
        name: "Exeggcute",
        description: "Though it may look like it’s just a bunch of eggs, it’s a proper Pokémon. Exeggcute communicates with others of its kind via telepathy, apparently.", 
        evolves: true,
        evolutionId: 101, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Egg",
        image: "/assets/images/102.png", 
        type: ["Grass", "Psychic"], 
        weakness: ["Ghost", "Fire", "Flying", "Ice", "Dark", "Poison", "Bug"],
        height: "1'04\"", 
        weight: "5.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 102,
        number: "#103",
        name: "Exeggutor",
        description: "Each of Exeggutor’s three heads is thinking different thoughts. The three don’t seem to be very interested in one another.", 
        evolves: false,
        evolutionId: 101, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Coconut",
        image: "/assets/images/103.png", 
        type: ["Grass", "Psychic"], 
        weakness: ["Ghost", "Fire", "Flying", "Ice", "Dark", "Poison", "Bug"],
        height: "6'07\"", 
        weight: "264.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 103,
        number: "#104",
        name: "Cubone",
        description: "When the memory of its departed mother brings it to tears, its cries echo mournfully within the skull it wears on its head..", 
        evolves: true,
        evolutionId: 103, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Lonely",
        image: "/assets/images/104.png", 
        type: ["Ground"], 
        weakness: ["Water", "Grass", "Ice"],
        height: "1'04\"", 
        weight: "14.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 104,
        number: "#105",
        name: "Marowak",
        description: "This Pokémon overcame its sorrow to evolve a sturdy new body. Marowak faces its opponents bravely, using a bone as a weapon.", 
        evolves: false,
        evolutionId: 103, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bone Keeper",
        image: "/assets/images/105.png", 
        type: ["Ground"], 
        weakness: ["Water", "Grass", "Ice"],
        height: "3'03\"", 
        weight: "99.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 105,
        number: "#106",
        name: "Hitmonlee",
        description: "This amazing Pokémon has an awesome sense of balance. It can kick in succession from any position.", 
        evolves: false,
        evolutionId: 105, 
        middleEvolution: false,
        baby: false,
        gender: ["Male"],
        category: "Kicking",
        image: "/assets/images/106.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying", "Fairy"],
        height: "4'11\"", 
        weight: "109.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 106,
        number: "#107",
        name: "Hitmonchan",
        description: "Its punches slice the air. They are launched at such high speed, even a slight graze could cause a burn.", 
        evolves: false,
        evolutionId: 106, 
        middleEvolution: false,
        baby: false,
        gender: ["Male"],
        category: "Punching",
        image: "/assets/images/107.png", 
        type: ["Fighting"], 
        weakness: ["Psychic", "Flying", "Fairy"],
        height: "4'07\"", 
        weight: "110.7 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 107,
        number: "#108",
        name: "Lickitung",
        description: "If this Pokémon’s sticky saliva gets on you and you don’t clean it off, an intense itch will set in. The itch won’t go away, either.", 
        evolves: false,
        evolutionId: 107,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Licking",
        image: "/assets/images/108.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "3'11\"", 
        weight: "144.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 108,
        number: "#109",
        name: "Koffing",
        description: "Its body is full of poisonous gas. It floats into garbage dumps, seeking out the fumes of raw, rotting trash.", 
        evolves: true,
        evolutionId: 108,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Poison Gas",
        image: "/assets/images/109.png", 
        type: ["Poison"], 
        weakness: ["Ground", "Psychic"],
        height: "2'00\"", 
        weight: "2.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 109,
        number: "#110",
        name: "Weezing",
        description: "It mixes gases between its two bodies. It’s said that these Pokémon were seen all over the Galar region back in the day.", 
        evolves: false,
        evolutionId: 109,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Poison Gas",
        image: "/assets/images/110.png", 
        type: ["Poison"], 
        weakness: ["Ground", "Psychic"],
        height: "3'11\"", 
        weight: "20.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 110,
        number: "#111",
        name: "Rhyhorn",
        description: "Strong, but not too bright, this Pokémon can shatter even a skyscraper with its charging tackles.", 
        evolves: true,
        evolutionId: 110,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Spikes",
        image: "/assets/images/111.png", 
        type: ["Ground", "Rock"], 
        weakness: ["Water", "Ground", "Steel", "Ice", "Fighting", "Grass"],
        height: "3'03\"", 
        weight: "253.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 111,
        number: "#112",
        name: "Rhydon",
        description: "It begins walking on its hind legs after evolution. It can punch holes through boulders with its horn.", 
        evolves: false,
        evolutionId: 110,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Drill",
        image: "/assets/images/112.png", 
        type: ["Ground", "Rock"], 
        weakness: ["Water", "Ground", "Steel", "Ice", "Fighting", "Grass"],
        height: "6'03\"", 
        weight: "264.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 112,
        number: "#113",
        name: "Chansey",
        description: "The egg Chansey carries is not only delicious but also packed with nutrition. It’s used as a high-class cooking ingredient.", 
        evolves: false,
        evolutionId: 112,
        middleEvolution: true,
        baby: false,
        gender: ["Female"],
        category: "Egg",
        image: "/assets/images/113.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "3'07\"", 
        weight: "76.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 113,
        number: "#114",
        name: "Tangela",
        description: "Hidden beneath a tangle of vines that grows nonstop even if the vines are torn off, this Pokémon’s true appearance remains a mystery.", 
        evolves: false,
        evolutionId: 113,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Vine",
        image: "/assets/images/114.png", 
        type: ["Grass"], 
        weakness: ["Fire", "Flying", "Ice", "Poison", "Bug"],
        height: "3'03\"", 
        weight: "77.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 114,
        number: "#115",
        name: "Kangaskhan",
        description: "Although it’s carrying its baby in a pouch on its belly, Kangaskhan is swift on its feet. It intimidates its opponents with quick jabs.", 
        evolves: false,
        evolutionId: 114,
        middleEvolution: true,
        baby: false,
        gender: ["Female"],
        category: "Parent",
        image: "/assets/images/115.png", 
        type: ["Normal"], 
        weakness: ["Fighting" ],
        height: "7'03\"", 
        weight: "176.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 115,
        number: "#116",
        name: "Horsea",
        description: "Horsea makes its home in oceans with gentle currents. If this Pokémon is under attack, it spits out pitch-black ink and escapes.", 
        evolves: true,
        evolutionId: 116, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dragon",
        image: "/assets/images/116.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "1'04\"", 
        weight: "17.6 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 116,
        number: "#117",
        name: "Seadra",
        description: "It’s the males that raise the offspring. While Seadra are raising young, the spines on their backs secrete thicker and stronger poison.", 
        evolves: false,
        evolutionId: 116, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dragon",
        image: "/assets/images/117.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'11\"", 
        weight: "55.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 117,
        number: "#118",
        name: "Goldeen",
        description: "Its dorsal, pectoral, and tail fins wave elegantly in water. That is why it is known as the Water Dancer..", 
        evolves: true,
        evolutionId: 117, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Goldfish",
        image: "/assets/images/118.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "2'00\"", 
        weight: "33.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 118,
        number: "#119",
        name: "Seaking",
        description: "In autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors.", 
        evolves: false,
        evolutionId: 117, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Goldfish",
        image: "/assets/images/119.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "4'03\"", 
        weight: "86.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 119,
        number: "#120",
        name: "Staryu",
        description: "If you visit a beach at the end of summer, you’ll be able to see groups of Staryu lighting up in a steady rhythm.", 
        evolves: true,
        evolutionId: 119, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Star Shape",
        image: "/assets/images/120.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "2'07\"", 
        weight: "76.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 120,
        number: "#121",
        name: "Starmie",
        description: "This Pokémon has an organ known as its core. The organ glows in seven colors when Starmie is unleashing its potent psychic powers..", 
        evolves: false,
        evolutionId: 119, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Mysterious",
        image: "/assets/images/121.png", 
        type: ["Water", "Psychic"], 
        weakness: ["Grass", "Electric", "Ghost", "Dark", "Bug"],
        height: "3'07\"", 
        weight: "176.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 121,
        number: "#122",
        name: "Mr. Mime",
        description: "The broadness of its hands may be no coincidence—many scientists believe its palms became enlarged specifically for pantomiming.", 
        evolves: false,
        evolutionId: 122, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Barrier",
        image: "/assets/images/122.png", 
        type: ["Psychic", "Fairy"], 
        weakness: ["Ghost", "Steel","Poison"],
        height: "4'03\"", 
        weight: "120.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 122,
        number: "#123",
        name: "Scyther",
        description: "As Scyther fights more and more battles, its scythes become sharper and sharper. With a single slice, Scyther can fell a massive tree.", 
        evolves: false,
        evolutionId: 122, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Mantis",
        image: "/assets/images/123.png", 
        type: ["Bug", "Flying"], 
        weakness: ["Fire", "Flying","Electric", "Ice", "Rock"],
        height: "4'11\"", 
        weight: "123.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 123,
        number: "#124",
        name: "Jynx",
        description: "In certain parts of Galar, Jynx was once feared and worshiped as the Queen of Ice.", 
        evolves: false,
        evolutionId: 123, 
        middleEvolution: false,
        baby: false,
        gender: ["Female"],
        category: "Human Shape",
        image: "/assets/images/124.png", 
        type: ["Ice", "Psychic"], 
        weakness: ["Steel", "Ghost", "Fire", "Dark", "Rock", "Bug"],
        height: "4'07\"", 
        weight: "89.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 124,
        number: "#125",
        name: "Electabuzz",
        description: "Many power plants keep Ground-type Pokémon around as a defense against Electabuzz that come seeking electricity.", 
        evolves: false,
        evolutionId: 124, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Electric",
        image: "/assets/images/125.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "3'07\"", 
        weight: "66.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 125,
        number: "#126",
        name: "Magmar",
        description: "Magmar dispatches its prey with fire. But it regrets this habit once it realizes that it has burned its intended prey to a charred crisp.", 
        evolves: false,
        evolutionId: 125, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Spitfire",
        image: "/assets/images/126.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "4'03\"", 
        weight: "98.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 126,
        number: "#127",
        name: "Pinsir",
        description: "These Pokémon judge one another based on pincers. Thicker, more impressive pincers make for more popularity with the opposite gender.", 
        evolves: false,
        evolutionId: 126, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Stag Beetle",
        image: "/assets/images/127.png", 
        type: ["Bug"], 
        weakness: ["Fire", "FLying", "Rock"],
        height: "4'11\"", 
        weight: "121.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 127,
        number: "#128",
        name: "Tauros",
        description: "When Tauros begins whipping itself with its tails, it’s a warning that the Pokémon is about to charge with astounding speed.", 
        evolves: false,
        evolutionId: 127, 
        middleEvolution: false,
        baby: false,
        gender: ["Male"],
        category: "Wild Bull",
        image: "/assets/images/128.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "4'07\"", 
        weight: "194.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 128,
        number: "#129",
        name: "Magikarp",
        description: "It is virtually worthless in terms of both power and speed. It is the most weak and pathetic Pokémon in the world.", 
        evolves: true,
        evolutionId: 128, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Fish",
        image: "/assets/images/129.png", 
        type: ["Water"], 
        weakness: ["Electric", "Grass"],
        height: "2'11\"", 
        weight: "22.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 129,
        number: "#130",
        name: "Gyarados",
        description: "It has an extremely aggressive nature. The Hyper Beam it shoots from its mouth totally incinerates all targets.", 
        evolves: false,
        evolutionId: 128, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Atrocious",
        image: "/assets/images/130.png", 
        type: ["Water", "Flying"], 
        weakness: ["Electric", "Rock"],
        height: "21'04\"", 
        weight: "518.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 130,
        number: "#131",
        name: "Lapras",
        description: "A smart and kindhearted Pokémon, it glides across the surface of the sea while its beautiful song echoes around it.", 
        evolves: false,
        evolutionId: 130, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Transport",
        image: "/assets/images/131.png", 
        type: ["Water", "Ice"], 
        weakness: ["Grass", "Electric", "Fighting", "Rock"],
        height: "8'02\"", 
        weight: "485.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 131,
        number: "#132",
        name: "Ditto",
        description: "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.", 
        evolves: false,
        evolutionId: 131, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Transform",
        image: "/assets/images/132.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "1'00\"", 
        weight: "8.8 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 132,
        number: "#133",
        name: "Evee",
        description: "It has the ability to alter the composition of its body to suit its surrounding environment.", 
        evolves: true,
        evolutionId: 132, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Evolution",
        image: "/assets/images/133.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "1'00\"", 
        weight: "14.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 133,
        number: "#134",
        name: "Vaporeon",
        description: "When Vaporeon’s fins begin to vibrate, it is a sign that rain will come within a few hours.", 
        evolves: false,
        evolutionId: 132, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Bubble Jet",
        image: "/assets/images/134.png", 
        type: ["Water"], 
        weakness: ["Grass", "Electric"],
        height: "3'03\"", 
        weight: "63.9 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 134,
        number: "#135",
        name: "Jolteon",
        description: "If it is angered or startled, the fur all over its body bristles like sharp needles that pierce foes.", 
        evolves: false,
        evolutionId: 132,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Lightning",
        image: "/assets/images/135.png", 
        type: ["Electric"], 
        weakness: ["Ground"],
        height: "2'07\"", 
        weight: "54.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 135,
        number: "#136",
        name: "Flareon",
        description: "Once it has stored up enough heat, this Pokémon’s body temperature can reach up to 1,700 degrees Fahrenheit.", 
        evolves: false,
        evolutionId: 132,
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Flame",
        image: "/assets/images/136.png", 
        type: ["Fire"], 
        weakness: ["Water", "Ground", "Rock"],
        height: "2'11\"", 
        weight: "55.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 136,
        number: "#137",
        name: "Porygon",
        description: "State-of-the-art technology was used to create Porygon. It was the first artificial Pokémon to be created via computer programming.", 
        evolves: false,
        evolutionId: 136,
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Virtual",
        image: "/assets/images/137.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "2'07\"", 
        weight: "80.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 137,
        number: "#138",
        name: "Omanyte",
        description: "Because some Omanyte manage to escape after being restored or are released into the wild by people, this species is becoming a problem.", 
        evolves: true,
        evolutionId: 137,
        middleEvolution: false,
        baby: false,
        fossil: true,
        gender: ["Female", "Male"],
        category: "Spiral",
        image: "/assets/images/138.png", 
        type: ["Rock", "Water"], 
        weakness: ["Grass", "Electric", "Ground", "Fighting"],
        height: "1'04\"", 
        weight: "16.5 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 138,
        number: "#139",
        name: "Omastar",
        description: "Weighed down by a large and heavy shell, Omastar couldn’t move very fast. Some say it went extinct because it was unable to catch food.", 
        evolves: false,
        evolutionId: 137,
        middleEvolution: false,
        baby: false,
        fossil: true,
        gender: ["Female", "Male"],
        category: "Spiral",
        image: "/assets/images/139.png", 
        type: ["Rock", "Water"], 
        weakness: ["Grass", "Electric", "Ground", "Fighting"],
        height: "3'03\"", 
        weight: "77.2 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 139,
        number: "#140",
        name: "Kabuto",
        description: "This species is almost entirely extinct. Kabuto molt every three days, making their shells harder and harder.", 
        evolves: true,
        evolutionId: 139,
        middleEvolution: false,
        baby: false,
        fossil: true,
        gender: ["Female", "Male"],
        category: "Shellfish",
        image: "/assets/images/140.png", 
        type: ["Rock", "Water"], 
        weakness: ["Grass", "Electric", "Ground", "Fighting"],
        height: "1'08\"", 
        weight: "25.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 140,
        number: "#141",
        name: "Kabutops",
        description: "Kabutops slices its prey apart and sucks out the fluids. The discarded body parts become food for other Pokémon.", 
        evolves: false,
        evolutionId: 139, 
        middleEvolution: false,
        baby: false,
        fossil: true,
        gender: ["Female", "Male"],
        category: "Shellfish",
        image: "/assets/images/141.png", 
        type: ["Rock", "Water"], 
        weakness: ["Grass", "Electric", "Ground", "Fighting"],
        height: "4'03\"", 
        weight: "89.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 141,
        number: "#142",
        name: "Areodactyl",
        description: "This is a ferocious Pokémon from ancient times. Apparently even modern technology is incapable of producing a perfectly restored specimen.", 
        evolves: false,
        evolutionId: 141, 
        middleEvolution: false,
        baby: false,
        fossil: true,
        gender: ["Female", "Male"],
        category: "Fossil",
        image: "/assets/images/142.png", 
        type: ["Rock", "Flying"], 
        weakness: ["Steel", "Water", "Electric", "Ice", "Rock"],
        height: "5'11\"", 
        weight: "130.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 142,
        number: "#143",
        name: "Snorlax",
        description: "It is not satisfied unless it eats over 880 pounds of food every day. When it is done eating, it goes promptly to sleep.", 
        evolves: false,
        evolutionId: 142, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Sleeping",
        image: "/assets/images/143.png", 
        type: ["Normal"], 
        weakness: ["Fighting"],
        height: "6'11\"", 
        weight: "1014.1 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 143,
        number: "#144",
        name: "Articuno",
        description: "It’s said that this Pokémon’s beautiful blue wings are made of ice. Articuno flies over snowy mountains, its long tail fluttering along behind it.", 
        evolves: false,
        evolutionId: 143, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Freeze",
        image: "/assets/images/144.png", 
        type: ["Ice", "Flying"], 
        weakness: ["Fire", "Electric", "Steel", "Rock"],
        height: "5'07\"", 
        weight: "122.1 LBS",
        generation: "1",
        caught: false,
        legendary: true
    },
    {
        id: 144,
        number: "#145",
        name: "Zapdos",
        description: "This Pokémon has complete control over electricity. There are tales of Zapdos nesting in the dark depths of pitch-black thunderclouds.", 
        evolves: false,
        evolutionId: 144, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Electric",
        image: "/assets/images/145.png", 
        type: ["Electric", "Flying"], 
        weakness: ["Ice", "Rock"],
        height: "5'03\"", 
        weight: "116.0 LBS",
        generation: "1",
        caught: false,
        legendary: true
    },
    {
        id: 145,
        number: "#146",
        name: "Moltres",
        description: "It’s one of the legendary bird Pokémon. When Moltres flaps its flaming wings, they glimmer with a dazzling red glow.", 
        evolves: false,
        evolutionId: 145, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "Flame",
        image: "/assets/images/146.png", 
        type: ["Fire", "Flying"], 
        weakness: ["Water", "Electric", "Rock"],
        height: "6'07\"", 
        weight: "132.3 LBS",
        generation: "1",
        caught: false,
        legendary: true
    },
    {
        id: 146,
        number: "#147",
        name: "Dratini",
        description: "Dratini dwells near bodies of rapidly flowing water, such as the plunge pools of waterfalls. As it grows, Dratini will shed its skin many times.", 
        evolves: true,
        evolutionId: 146, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dragon",
        image: "/assets/images/147.png", 
        type: ["Dragon"], 
        weakness: ["Fairy", "Ice", "Dragon"],
        height: "5'11\"", 
        weight: "7.3 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 147,
        number: "#148",
        name: "Dragonair",
        description: "This Pokémon lives in pristine oceans and lakes. It can control the weather, and it uses this power to fly into the sky, riding on the wind.", 
        evolves: true,
        evolutionId: 146, 
        middleEvolution: true,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dragon",
        image: "/assets/images/148.png", 
        type: ["Dragon"], 
        weakness: ["Fairy", "Ice", "Dragon"],
        height: "13'01\"", 
        weight: "36.4 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 148,
        number: "#149",
        name: "Dragonite",
        description: "It’s a kindhearted Pokémon. If it spots a drowning person or Pokémon, Dragonite simply must help them.", 
        evolves: false,
        evolutionId: 146, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Dragon",
        image: "/assets/images/149.png", 
        type: ["Dragon", "Flying"], 
        weakness: ["Fairy", "Ice","Dragon", "Rock"],
        height: "7'03\"", 
        weight: "463.0 LBS",
        generation: "1",
        caught: false,
        legendary: false
    },
    {
        id: 149,
        number: "#150",
        name: "Mewtwo",
        description: "Its DNA is almost the same as Mew’s. However, its size and disposition are vastly different.", 
        evolves: false,
        evolutionId: 149, 
        middleEvolution: false,
        baby: false,
        gender: ["Female", "Male"],
        category: "Genetic",
        image: "/assets/images/150.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark", "Bug"],
        height: "6'07\"", 
        weight: "269.0 LBS",
        generation: "1",
        caught: false,
        legendary: true
    },
    {
        id: 150,
        number: "#151",
        name: "Mew",
        description: "When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.", 
        evolves: false,
        evolutionId: 150, 
        middleEvolution: false,
        baby: false,
        gender: ["Unknown"],
        category: "New Species",
        image: "/assets/images/151.png", 
        type: ["Psychic"], 
        weakness: ["Ghost", "Dark", "Bug"],
        height: "1'04\"", 
        weight: "8.8 LBS",
        generation: "1",
        caught: false,
        legendary: true
    }
]
