export const ADD_POKEMON = 'ADD_POKEMON';

export const ADD_GYM_LEADERS = 'ADD_GYM_LEADERS';

export const POST_SAVED_TEAM = 'POST_SAVED_TEAM';
export const ADD_SAVED_TEAM = 'ADD_SAVED_TEAM';

export const POST_CAUGHT_POKEMON = 'POST_CAUGHT_POKEMON';
export const ADD_CAUGHT_POKEMON = 'ADD_CAUGHT_POKEMON';

export const ADD_LOCATION = 'ADD_LOCATION'